# Generated by Django 5.1.1 on 2024-10-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_usermodel_first_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='can_add_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
