# Generated by Django 5.1.1 on 2024-10-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_usermodel_can_add_admin_usermodel_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_join',
            field=models.BooleanField(default=False),
        ),
    ]
