# Generated by Django 5.1.1 on 2024-10-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_usermodel_is_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='chat_id',
            field=models.IntegerField(default=123123),
            preserve_default=False,
        ),
    ]
