# Generated by Django 5.1.1 on 2024-10-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_usermodel_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_channel_username', models.CharField(max_length=100)),
            ],
        ),
    ]
