# Generated by Django 5.1.1 on 2024-10-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_channelmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='placeInBot',
            field=models.IntegerField(choices=[(0, 'بدون مکان'), (1, 'افزودن ادمین'), (2, 'افزودن چنل')], default=0),
        ),
    ]
