# Generated by Django 5.1.1 on 2024-10-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_usermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='placeInBot',
            field=models.IntegerField(choices=[(0, 'بدون مکان'), (1, 'افزودن ادمین'), (2, 'افزودن چنل'), (3, 'دلت چنل')], default=0),
        ),
    ]
