# Generated by Django 5.1.1 on 2024-10-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_usermodel_placeinbot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_username', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='placeInBot',
            field=models.IntegerField(choices=[(0, 'بدون مکان'), (1, 'افزودن ادمین'), (2, 'افزودن چنل'), (3, 'دلت چنل'), (4, 'پیام همگانی')], default=0),
        ),
    ]
