# Generated by Django 5.1.1 on 2024-10-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_uservideo_alter_usermodel_placeinbot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserVideo',
            new_name='VideoModel',
        ),
    ]
