# Generated by Django 5.1.1 on 2024-10-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_rename_uservideo_videomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='video_id',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
