# Generated by Django 5.1.1 on 2024-10-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_videomodel_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='video_id',
            field=models.CharField(max_length=500),
        ),
    ]
