# Generated by Django 5.1.1 on 2024-10-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_alter_usermodel_placeinbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='postId',
            field=models.IntegerField(default=0),
        ),
    ]
