# Generated by Django 5.1.1 on 2024-10-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_usermodel_postid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='telegram_user_num',
        ),
    ]
