# Generated by Django 5.1.1 on 2024-10-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_remove_usermodel_telegram_user_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_username', models.CharField(max_length=100)),
                ('photo_id', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='chat_id',
            field=models.IntegerField(default=3232),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(blank=True, default='none', max_length=100, null=True),
        ),
    ]
