# Generated by Django 5.1.1 on 2024-10-07 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_photomodel_usermodel_chat_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomodel',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='photomodel',
            name='user_username',
        ),
        migrations.AddField(
            model_name='photomodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.usermodel'),
        ),
    ]
