# Generated by Django 5.1.1 on 2024-10-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_remove_photomodel_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='username',
            new_name='_username',
        ),
    ]
