# Generated by Django 5.1.1 on 2024-10-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_filemodel_remove_photomodel_user_delete_videomodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmodel',
            name='users',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
